// src/dashboard/client/components/utils/badge.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { SimpleChanges, OnChanges } from "@angular/core/index";
import { Subscription } from "rxjs";
import { Observable } from "rxjs/Observable";

@Component({
    selector: "badge",
    template: `
<button data-toggle="modal" [attr.data-target]="'#' + id" type="button"
    class="btn btn-outline no-padding" style="height:20px">
        <i class="fa fa-file-code-o"></i>
</button>

<img src="https://img.shields.io/badge/{{ subject }}-{{ statusEncoded }}-{{ color }}.svg" height="20px" />

<div id="{{ id }}" class="modal fade" aria-hidden="true">
    <div class="modal-dialog" style="width:50%">
        <div class="modal-content">
            <div class="modal-body">
                <div class="m-t-md m-b-lg">
                    <h2>Embed your badge</h2>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Markdown
                    </div>
                    <div class="panel-body">
                        <![CDATA[[![{{ subject }}]({{ url }})]({{ link }})]]>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        HTML
                    </div>
                    <div class="panel-body">
                        <![CDATA[<a href="{{ link }}"><img src="{{ url }}" alt="{{ subject }}"/></a>]]>
                    </div>

                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        RST
                    </div>
                    <div class="panel-body">
                        <![CDATA[.. image:: {{ url }} :target: {{ link }}]]>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Textile
                    </div>
                    <div class="panel-body">
                        <![CDATA[!{{ url }}({{ subject }})!:{{ link }}]]>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        RDOC
                    </div>
                    <div class="panel-body">
                        <![CDATA[{<img src="{{ url }}" alt="{{ subject }}"/>}[{{ link }}]]]>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
`,
})
export class BadgeComponent implements OnInit, OnChanges {
    @Input() private subject: string;
    @Input() private status: string;
    @Input() private color: string;
    @Input() private project_id: string;
    @Input() private job_name: string;
    private api_host: string;
    private dashboard_host: string;
    private id: string;
    private url: string;
    private link: string;
    private statusEncoded: string;

    constructor() {
        this.api_host = window['INFRABOX_API_URL'];
        this.dashboard_host = window['INFRABOX_DASHBOARD_URL'];
    }

    public ngOnInit() {
        this.init();
    }

    public ngOnChanges(changes: SimpleChanges) {
        this.init();
    }

    private init() {
        this.statusEncoded = encodeURI(this.status);
        this.id = `badge-${this.subject}-${this.status}`;
        this.id = this.id.replace(/\W+/g, "");
        this.url = `${this.api_host}/v1/project/${this.project_id}/badge.svg?subject=${this.subject}&job_name=${this.job_name}`;
        this.url = encodeURI(this.url);
        this.link = `${this.dashboard_host}/dashboard/project/${this.project_id}`;
    }
}

// src/dashboard-client/src/components/utils/Badge.vue
<template>
    <span>
            <span>
                <img :src="badgeUrl" height="20px" />
                <md-button class="md-icon-button" @click="openDialog(dialog_id)" style="padding-left:-16px; margin-left: -16px">
                    <i class="fa fa-fw fa-file-code-o" style="font-size: 19px; color: #757575"></i>
                </md-button>
            </span>
        <md-dialog md-open-from="#fab" md-close-to="#fab" :ref="dialog_id" width="100%">
            <md-dialog-title>Embed your badge</md-dialog-title>

            <md-dialog-content class="bg-white">
                <md-card class="main-card">
                    <div class="md-subtitle bg-light p-md">Markdown</div>
                    <div class="m-md">{{ markdown }}</div>
                </md-card>
                <md-card class="main-card">
                    <div class="md-subtitle bg-light p-md">HTML</div>
                    <div class="m-md">{{ html }}</div>
                </md-card>
                <md-card class="main-card">
                    <div class="md-subtitle bg-light p-md">RST</div>
                    <div class="m-md">{{ rst }}</div>
                </md-card>
                <md-card class="main-card">
                    <div class="md-subtitle bg-light p-md">Textile</div>
                    <div class="m-md">{{ textile }} </div>
                </md-card>
                <md-card class="main-card">
                    <div class="md-subtitle bg-light p-md">RDOC</div>
                    <div class="m-md">{{ rdoc }}</div>
                </md-card>
            </md-dialog-content>
            <md-dialog-actions>
                <md-button class="md-icon-button md-primary" @click="closeDialog(dialog_id)"><md-icon>close</md-icon></md-button>
            </md-dialog-actions>
        </md-dialog>
    </span>
</template>

<script>
import store from '../../store'

export default {
    props: ['job', 'subject', 'status', 'color'],
    created () {
        this.dialog_id = `${this.job.name}_${this.subject}_dialog`
        this.api_host = store.state.settings.INFRABOX_API_URL
        this.dashboard_host = store.state.settings.INFRABOX_DASHBOARD_URL
        this.statusEncoded = encodeURI(this.status)
        this.id = `badge-${this.subject}-${this.status}`
        this.id = this.id.replace(/\W+/g, '')
        this.url = `${this.api_host}/v1/project/${this.job.project.id}/badge.svg?subject=${this.subject}&job_name=${this.job.name}`
        this.url = encodeURI(this.url)
        this.link = `${this.dashboard_host}/dashboard/#/project/${this.job.project.name}`
        this.badgeUrl = `https://img.shields.io/badge/${this.subject}-${this.statusEncoded}-${this.color}.svg`
        this.markdown = `[![${this.subject}](${this.url})](${this.link})`
        this.html = `<a href="${this.link}"><img src="${this.url}" alt="${this.subject}"/></a>`
        this.rst = `.. image:: ${this.url} :target: ${this.link}`
        this.textile = `!${this.url}(${this.subject})!:${this.link}`
        this.rdoc = `{<img src="${this.url}" alt="${this.subject}"/>}[${this.link}]`
    },
    methods: {
        openDialog (ref) {
            this.$refs[ref].open()
        },
        closeDialog (ref) {
            this.$refs[ref].close()
        }
    }
}
</script>

<style scoped>
    .small-font{
        font-size: 13px;
    }
</style>
